apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-resizer-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: image-resizer
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: image-resizer
    spec:
      containers:
      - name: image-resizer
        image: abrinkop/image-resizer-microservice:$BUILD_NUMBER # replaced by Jenkins
        ports:
        - containerPort: 3000


apiVersion: v1
kind: Service
metadata:
  name: image-resizer-service
spec:
  selector:
    app: image-resizer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer